theme: jekyll-theme-hacker
title: LightApi
description: Documentation of LightApi framework
show_downloads: true
github:
  zip_url: https://github.com/pjpawel/LightApi/zipball/main
  tar_url: https://github.com/pjpawel/LightApi/tarball/main
  repository_url: https://github.com/pjpawel/LightApi
